services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.debug
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    command: [ "/bin/sh", "-c", "while sleep 1000; do :; done" ]
    build:
      context: ./backend
      dockerfile: Dockerfile.debug
    working_dir: /workspace
    ports:
      - "5000:5000"
    volumes:
      - .:/workspace
      - ./backend:/app/backend
      - ./shared:/app/shared
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000

networks:
  default:
    driver: bridge
