version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    network_mode: "host"
    volumes:
      - ./shared:/app/shared
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:5000

networks:
  default:
    driver: bridge
