services:
  backend:
    command: [ "/bin/sh", "-c", "while sleep 1000; do :; done" ]
    build:
      context: ./backend
      dockerfile: Dockerfile.debug
    working_dir: /workspace
    network_mode: "host"
    volumes:
      - .:/workspace
      - ./backend:/app/backend
      - ./shared:/app/shared
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000

networks:
  default:
    driver: bridge
